apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-mg-cart-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  
spec:
  project: default

  source:
    path: application
    repoURL: git@github.com:Poonnachit/mg-argocd.git
    targetRevision: HEAD
    directory:
      recurse: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true 
      selfHeal: true