apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-pedjeab-config
  namespace: argocd
spec:
  project: default
  source:
    path: develop/pedjeab
    repoURL: 'git@github.com:Poonnachit/mg-non-prod-config.git'
    targetRevision: HEAD
  destination:
    namespace: develop
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true